USE [master]
GO

/****** Object:  Database [DBTreinamento]    Script Date: 16/11/2021 00:53:20 ******/
CREATE DATABASE [DBTreinamento]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBTreinamento].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBTreinamento] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBTreinamento] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBTreinamento] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBTreinamento] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBTreinamento] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBTreinamento] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBTreinamento] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBTreinamento] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBTreinamento] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBTreinamento] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBTreinamento] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBTreinamento] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBTreinamento] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBTreinamento] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBTreinamento] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBTreinamento] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBTreinamento] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBTreinamento] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBTreinamento] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBTreinamento] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBTreinamento] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBTreinamento] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBTreinamento] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBTreinamento] SET  MULTI_USER 
GO

ALTER DATABASE [DBTreinamento] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBTreinamento] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBTreinamento] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBTreinamento] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBTreinamento] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBTreinamento] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBTreinamento] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBTreinamento] SET  READ_WRITE 
GO


